Add image push workflow (#63)
* Adjust vitess-env build configuration

* Add image push workflow

Co-authored-by: wanghaoyang11 <wanghaoyang11@jd.com>

diff --git a/src/test/resources/vitess_env/vtdriver-env-v11.0.0.patch b/src/test/resources/vitess_env/vtdriver-env-v11.0.0.patch
--- a/src/test/resources/vitess_env/vtdriver-env-v11.0.0.patch
+++ b/src/test/resources/vitess_env/vtdriver-env-v11.0.0.patch
@@ -1,74 +1,82 @@
-Index: Makefile
+Index: examples/local/vtdriver/vttablet-up.sh
 IDEA additional info:
 Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
 <+>UTF-8
 ===================================================================
-diff --git a/Makefile b/Makefile
---- a/Makefile	(revision bc4a9606e1899a4223b80edfb212f32af81000ac)
-+++ b/Makefile	(date 1646038256067)
-@@ -293,6 +293,9 @@
- docker_local:
- 	${call build_docker_image,docker/local/Dockerfile,vitess/local}
- 
-+docker_vtdriver:
-+	${call build_docker_image,docker/local/Dockerfile.vtdriver,vtdriverio/vtdriver-env}
-+
- docker_run_local:
- 	./docker/local/run.sh
- 
-Index: docker/local/Dockerfile.vtdriver
-IDEA additional info:
-Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
-<+>UTF-8
-===================================================================
-diff --git a/docker/local/Dockerfile.vtdriver b/docker/local/Dockerfile.vtdriver
+diff --git a/examples/local/vtdriver/vttablet-up.sh b/examples/local/vtdriver/vttablet-up.sh
 new file mode 100644
---- /dev/null	(date 1646038396047)
-+++ b/docker/local/Dockerfile.vtdriver	(date 1646038396047)
-@@ -0,0 +1,43 @@
-+ARG bootstrap_version=4
-+ARG image="vitess/bootstrap:${bootstrap_version}-common"
+--- /dev/null	(date 1646119171073)
++++ b/examples/local/vtdriver/vttablet-up.sh	(date 1646119171073)
+@@ -0,0 +1,69 @@
++#!/bin/bash
 +
-+FROM "${image}"
++# Copyright 2019 The Vitess Authors.
++# 
++# Licensed under the Apache License, Version 2.0 (the "License");
++# you may not use this file except in compliance with the License.
++# You may obtain a copy of the License at
++# 
++#     http://www.apache.org/licenses/LICENSE-2.0
++# 
++# Unless required by applicable law or agreed to in writing, software
++# distributed under the License is distributed on an "AS IS" BASIS,
++# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
++# See the License for the specific language governing permissions and
++# limitations under the License.
 +
-+RUN apt-get update
-+RUN apt-get install -y sudo curl vim jq
++source ./vtdriver/env.sh # source ./env.sh
 +
-+# Install dependencies
-+COPY docker/lite/install_dependencies.sh /vt/dist/install_dependencies.sh
-+RUN /vt/dist/install_dependencies.sh mysql57
++cell=${CELL:-'test'}
++keyspace=${KEYSPACE:-'test_keyspace'}
++shard=${SHARD:-'0'}
++uid=$TABLET_UID
++mysql_port=$[17000 + $uid]
++port=$[15000 + $uid]
++grpc_port=$[16000 + $uid]
++printf -v alias '%s-%010d' $cell $uid
++printf -v tablet_dir 'vt_%010d' $uid
++tablet_hostname=${hostname} # tablet_hostname=''
++printf -v tablet_logfile 'vttablet_%010d_querylog.txt' $uid
 +
-+COPY docker/local/install_local_dependencies.sh /vt/dist/install_local_dependencies.sh
-+RUN /vt/dist/install_local_dependencies.sh
-+RUN echo "source /vt/local/env.sh" >> /etc/bash.bashrc
++tablet_type=replica
++if [[ "${uid: -1}" -gt 1 ]]; then
++ tablet_type=rdonly
++fi
 +
-+# Allows some docker builds to disable CGO
-+ARG CGO_ENABLED=0
++echo "Starting vttablet for $alias..."
++# shellcheck disable=SC2086
++vttablet \
++ $TOPOLOGY_FLAGS \
++ -log_dir $VTDATAROOT/tmp \
++ -log_queries_to_file $VTDATAROOT/tmp/$tablet_logfile \
++ -tablet-path $alias \
++ -tablet_hostname "$tablet_hostname" \
++ -init_keyspace $keyspace \
++ -init_shard $shard \
++ -init_tablet_type $tablet_type \
++ -health_check_interval 5s \
++ -enable_semi_sync \
++ -enable_replication_reporter \
++ -backup_storage_implementation file \
++ -file_backup_storage_root $VTDATAROOT/backups \
++ -restore_from_backup \
++ -port $port \
++ -grpc_port $grpc_port \
++ -service_map 'grpc-queryservice,grpc-tabletmanager,grpc-updatestream' \
++ -pid_file $VTDATAROOT/$tablet_dir/vttablet.pid \
++ -vtctld_addr http://$hostname:$vtctld_web_port/ \
++ > $VTDATAROOT/$tablet_dir/vttablet.out 2>&1 &
 +
-+# Re-copy sources from working tree.
-+COPY --chown=vitess:vitess . /vt/src/vitess.io/vitess
++# Block waiting for the tablet to be listening
++# Not the same as healthy
 +
-+# Build and install Vitess in a temporary output directory.
-+USER vitess
++for i in $(seq 0 300); do
++ curl -I "http://$hostname:$port/debug/status" >/dev/null 2>&1 && break
++ sleep 0.1
++done
 +
-+WORKDIR /vt/src/vitess.io/vitess
-+RUN make install PREFIX=/vt/install
-+
-+ENV VTROOT /vt/src/vitess.io/vitess
-+ENV VTDATAROOT /vt/vtdataroot
-+ENV PATH $VTROOT/bin:$PATH
-+ENV PATH="/var/opt/etcd:${PATH}"
-+
-+RUN mkdir /vt/local
-+RUN cp -r /vt/src/vitess.io/vitess/examples/local/* /vt/local
-+# COPY examples/local /vt/local
-+
-+RUN mkdir /vt/common
-+RUN cp -r /vt/src/vitess.io/vitess/examples/common/* /vt/common
-+# COPY examples/common /vt/common
-+
-+
-+CMD cd /vt/local && ./vtdriver/vtdriver_init.sh && /bin/bash
++# check one last time
++curl -I "http://$hostname:$port/debug/status" || fail "tablet could not be started!"
 Index: examples/local/vtdriver/vtgate-up.sh
 IDEA additional info:
 Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
@@ -76,8 +84,8 @@ Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
 ===================================================================
 diff --git a/examples/local/vtdriver/vtgate-up.sh b/examples/local/vtdriver/vtgate-up.sh
 new file mode 100644
---- /dev/null	(date 1646035854007)
-+++ b/examples/local/vtdriver/vtgate-up.sh	(date 1646035854007)
+--- /dev/null	(date 1646119171053)
++++ b/examples/local/vtdriver/vtgate-up.sh	(date 1646119171053)
 @@ -0,0 +1,57 @@
 +#!/bin/bash
 +
@@ -117,7 +125,7 @@ new file mode 100644
 +  -mysql_server_socket_path $mysql_server_socket_path \
 +  -cell $cell \
 +  -cells_to_watch $cell \
-+  -tablet_types_to_wait PRIMARY,REPLICA \
++  -tablet_types_to_wait MASTER,REPLICA \
 +  -service_map 'grpc-vtgateservice' \
 +  -pid_file $VTDATAROOT/tmp/vtgate.pid \
 +  -mysql_auth_server_impl none \
@@ -136,86 +144,6 @@ new file mode 100644
 +echo "Access vtgate at http://$hostname:$web_port/debug/status"
 +
 +disown -a
-Index: examples/local/vtdriver/vttablet-up.sh
-IDEA additional info:
-Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
-<+>UTF-8
-===================================================================
-diff --git a/examples/local/vtdriver/vttablet-up.sh b/examples/local/vtdriver/vttablet-up.sh
-new file mode 100644
---- /dev/null	(date 1646038695087)
-+++ b/examples/local/vtdriver/vttablet-up.sh	(date 1646038695087)
-@@ -0,0 +1,70 @@
-+#!/bin/bash
-+
-+# Copyright 2019 The Vitess Authors.
-+# 
-+# Licensed under the Apache License, Version 2.0 (the "License");
-+# you may not use this file except in compliance with the License.
-+# You may obtain a copy of the License at
-+# 
-+#     http://www.apache.org/licenses/LICENSE-2.0
-+# 
-+# Unless required by applicable law or agreed to in writing, software
-+# distributed under the License is distributed on an "AS IS" BASIS,
-+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-+# See the License for the specific language governing permissions and
-+# limitations under the License.
-+
-+source ./vtdriver/env.sh # source ./env.sh
-+
-+cell=${CELL:-'test'}
-+keyspace=${KEYSPACE:-'test_keyspace'}
-+shard=${SHARD:-'0'}
-+uid=$TABLET_UID
-+mysql_port=$[17000 + $uid]
-+port=$[15000 + $uid]
-+grpc_port=$[16000 + $uid]
-+printf -v alias '%s-%010d' $cell $uid
-+printf -v tablet_dir 'vt_%010d' $uid
-+tablet_hostname=${hostname} # tablet_hostname=''
-+printf -v tablet_logfile 'vttablet_%010d_querylog.txt' $uid
-+
-+tablet_type=replica
-+if [[ "${uid: -1}" -gt 1 ]]; then
-+ tablet_type=rdonly
-+fi
-+
-+echo "Starting vttablet for $alias..."
-+
-+# shellcheck disable=SC2086
-+vttablet \
-+ $TOPOLOGY_FLAGS \
-+ -log_dir $VTDATAROOT/tmp \
-+ -log_queries_to_file $VTDATAROOT/tmp/$tablet_logfile \
-+ -tablet-path $alias \
-+ -tablet_hostname "$tablet_hostname" \
-+ -init_keyspace $keyspace \
-+ -init_shard $shard \
-+ -init_tablet_type $tablet_type \
-+ -health_check_interval 5s \
-+ -enable_semi_sync \
-+ -enable_replication_reporter \
-+ -backup_storage_implementation file \
-+ -file_backup_storage_root $VTDATAROOT/backups \
-+ -restore_from_backup \
-+ -port $port \
-+ -grpc_port $grpc_port \
-+ -service_map 'grpc-queryservice,grpc-tabletmanager,grpc-updatestream' \
-+ -pid_file $VTDATAROOT/$tablet_dir/vttablet.pid \
-+ -vtctld_addr http://$hostname:$vtctld_web_port/ \
-+ > $VTDATAROOT/$tablet_dir/vttablet.out 2>&1 &
-+
-+# Block waiting for the tablet to be listening
-+# Not the same as healthy
-+
-+for i in $(seq 0 300); do
-+ curl -I "http://$hostname:$port/debug/status" >/dev/null 2>&1 && break
-+ sleep 0.1
-+done
-+
-+# check one last time
-+curl -I "http://$hostname:$port/debug/status" || fail "tablet could not be started!"
 Index: examples/local/vtdriver/vtdriver_init.sh
 IDEA additional info:
 Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
@@ -223,8 +151,8 @@ Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
 ===================================================================
 diff --git a/examples/local/vtdriver/vtdriver_init.sh b/examples/local/vtdriver/vtdriver_init.sh
 new file mode 100644
---- /dev/null	(date 1646041658517)
-+++ b/examples/local/vtdriver/vtdriver_init.sh	(date 1646041658517)
+--- /dev/null	(date 1646118958343)
++++ b/examples/local/vtdriver/vtdriver_init.sh	(date 1646118958343)
 @@ -0,0 +1,141 @@
 +#!/bin/bash
 +
@@ -260,7 +188,7 @@ new file mode 100644
 +    done
 +
 +    # set one of the replicas to primary
-+    vtctldclient PlannedReparentShard --server 127.0.0.1:15999 commerce/0 --new-primary zone1-100
++    vtctldclient InitShardPrimary --server 127.0.0.1:15999 --force commerce/0 zone1-100
 +
 +    # Add remote user in MySQL
 +    for i in 100
@@ -367,67 +295,6 @@ new file mode 100644
 +else
 +    CELL=zone1 ./vtdriver/vtgate-up.sh
 +fi
-Index: examples/local/vtdriver/etcd-up.sh
-IDEA additional info:
-Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
-<+>UTF-8
-===================================================================
-diff --git a/examples/local/vtdriver/etcd-up.sh b/examples/local/vtdriver/etcd-up.sh
-new file mode 100644
---- /dev/null	(date 1646038695027)
-+++ b/examples/local/vtdriver/etcd-up.sh	(date 1646038695027)
-@@ -0,0 +1,51 @@
-+#!/bin/bash
-+
-+# Copyright 2019 The Vitess Authors.
-+# 
-+# Licensed under the Apache License, Version 2.0 (the "License");
-+# you may not use this file except in compliance with the License.
-+# You may obtain a copy of the License at
-+# 
-+#     http://www.apache.org/licenses/LICENSE-2.0
-+# 
-+# Unless required by applicable law or agreed to in writing, software
-+# distributed under the License is distributed on an "AS IS" BASIS,
-+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-+# See the License for the specific language governing permissions and
-+# limitations under the License.
-+
-+# This is an example script that creates a quorum of Etcd servers.
-+
-+source ./vtdriver/env.sh
-+
-+cell=${CELL:-'test'}
-+export ETCDCTL_API=2
-+
-+# Check that etcd is not already running
-+curl "http://${ETCD_SERVER}" > /dev/null 2>&1 && fail "etcd is already running. Exiting."
-+
-+etcd --enable-v2=true --data-dir "${VTDATAROOT}/etcd/"  --listen-client-urls "http://0.0.0.0:2379" --advertise-client-urls "http://${ETCD_SERVER}" > "${VTDATAROOT}"/tmp/etcd.out 2>&1 &
-+PID=$!
-+echo $PID > "${VTDATAROOT}/tmp/etcd.pid"
-+sleep 5
-+
-+echo "add /vitess/global"
-+etcdctl --endpoints "http://${ETCD_SERVER}" mkdir /vitess/global &
-+
-+echo "add /vitess/$cell"
-+etcdctl --endpoints "http://${ETCD_SERVER}" mkdir /vitess/$cell &
-+
-+# And also add the CellInfo description for the cell.
-+# If the node already exists, it's fine, means we used existing data.
-+echo "add $cell CellInfo"
-+set +e
-+# shellcheck disable=SC2086
-+vtctl $TOPOLOGY_FLAGS VtctldCommand AddCellInfo \
-+  --root /vitess/$cell \
-+  --server-address "${ETCD_SERVER}" \
-+  $cell
-+set -e
-+
-+echo "etcd start done..."
-+
-+
 Index: examples/local/vtdriver/vtctld-up.sh
 IDEA additional info:
 Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
@@ -435,9 +302,9 @@ Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
 ===================================================================
 diff --git a/examples/local/vtdriver/vtctld-up.sh b/examples/local/vtdriver/vtctld-up.sh
 new file mode 100644
---- /dev/null	(date 1646038695047)
-+++ b/examples/local/vtdriver/vtctld-up.sh	(date 1646038695047)
-@@ -0,0 +1,39 @@
+--- /dev/null	(date 1646118958323)
++++ b/examples/local/vtdriver/vtctld-up.sh	(date 1646118958323)
+@@ -0,0 +1,38 @@
 +#!/bin/bash
 +
 +# Copyright 2019 The Vitess Authors.
@@ -473,10 +340,88 @@ new file mode 100644
 + -file_backup_storage_root $VTDATAROOT/backups \
 + -log_dir $VTDATAROOT/tmp \
 + -port $vtctld_web_port \
-+ -durability_policy 'semi_sync' \
 + -grpc_port $grpc_port \
 + -pid_file $VTDATAROOT/tmp/vtctld.pid \
 +  > $VTDATAROOT/tmp/vtctld.out 2>&1 &
+Index: examples/local/vtdriver/etcd-up.sh
+IDEA additional info:
+Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
+<+>UTF-8
+===================================================================
+diff --git a/examples/local/vtdriver/etcd-up.sh b/examples/local/vtdriver/etcd-up.sh
+new file mode 100644
+--- /dev/null	(date 1646119171113)
++++ b/examples/local/vtdriver/etcd-up.sh	(date 1646119171113)
+@@ -0,0 +1,51 @@
++#!/bin/bash
++
++# Copyright 2019 The Vitess Authors.
++# 
++# Licensed under the Apache License, Version 2.0 (the "License");
++# you may not use this file except in compliance with the License.
++# You may obtain a copy of the License at
++# 
++#     http://www.apache.org/licenses/LICENSE-2.0
++# 
++# Unless required by applicable law or agreed to in writing, software
++# distributed under the License is distributed on an "AS IS" BASIS,
++# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
++# See the License for the specific language governing permissions and
++# limitations under the License.
++
++# This is an example script that creates a quorum of ZooKeeper servers.
++
++source ./vtdriver/env.sh
++
++cell=${CELL:-'test'}
++export ETCDCTL_API=2
++
++# Check that etcd is not already running
++curl "http://${ETCD_SERVER}" > /dev/null 2>&1 && fail "etcd is already running. Exiting."
++
++etcd --enable-v2=true --data-dir "${VTDATAROOT}/etcd/"  --listen-client-urls "http://0.0.0.0:2379" --advertise-client-urls "http://${ETCD_SERVER}" > "${VTDATAROOT}"/tmp/etcd.out 2>&1 &
++PID=$!
++echo $PID > "${VTDATAROOT}/tmp/etcd.pid"
++sleep 5
++
++echo "add /vitess/global"
++etcdctl --endpoints "http://${ETCD_SERVER}" mkdir /vitess/global &
++
++echo "add /vitess/$cell"
++etcdctl --endpoints "http://${ETCD_SERVER}" mkdir /vitess/$cell &
++
++# And also add the CellInfo description for the cell.
++# If the node already exists, it's fine, means we used existing data.
++echo "add $cell CellInfo"
++set +e
++# shellcheck disable=SC2086
++vtctl $TOPOLOGY_FLAGS AddCellInfo \
++  -root /vitess/$cell \
++  -server_address "${ETCD_SERVER}" \
++  $cell
++set -e
++
++echo "etcd start done..."
++
++
+Index: Makefile
+IDEA additional info:
+Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
+<+>UTF-8
+===================================================================
+diff --git a/Makefile b/Makefile
+--- a/Makefile	(revision aa798b854a0d12db8151157919108eaefb2378b2)
++++ b/Makefile	(date 1646118958403)
+@@ -295,6 +295,9 @@
+ docker_local:
+ 	${call build_docker_image,docker/local/Dockerfile,vitess/local}
+ 
++docker_vtdriver:
++	${call build_docker_image,docker/local/Dockerfile.vtdriver,vtdriverio/vtdriver-env}
++
+ docker_mini:
+ 	${call build_docker_image,docker/mini/Dockerfile,vitess/mini}
+ 
 Index: examples/local/vtdriver/env.sh
 IDEA additional info:
 Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
@@ -484,8 +429,8 @@ Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
 ===================================================================
 diff --git a/examples/local/vtdriver/env.sh b/examples/local/vtdriver/env.sh
 new file mode 100644
---- /dev/null	(date 1646035854007)
-+++ b/examples/local/vtdriver/env.sh	(date 1646035854007)
+--- /dev/null	(date 1646118958293)
++++ b/examples/local/vtdriver/env.sh	(date 1646118958293)
 @@ -0,0 +1,83 @@
 +#!/bin/bash
 +
@@ -570,3 +515,72 @@ new file mode 100644
 +# Make sure aliases are expanded in non-interactive shell
 +shopt -s expand_aliases
 +
+Index: docker/local/Dockerfile.vtdriver
+IDEA additional info:
+Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
+<+>UTF-8
+===================================================================
+diff --git a/docker/local/Dockerfile.vtdriver b/docker/local/Dockerfile.vtdriver
+new file mode 100644
+--- /dev/null	(date 1646119171093)
++++ b/docker/local/Dockerfile.vtdriver	(date 1646119171093)
+@@ -0,0 +1,43 @@
++ARG bootstrap_version=2
++ARG image="vitess/bootstrap:${bootstrap_version}-common"
++
++FROM "${image}"
++
++RUN apt-get update
++RUN apt-get install -y sudo curl vim jq
++
++# Install dependencies
++COPY docker/lite/install_dependencies.sh /vt/dist/install_dependencies.sh
++RUN /vt/dist/install_dependencies.sh mysql57
++
++COPY docker/local/install_local_dependencies.sh /vt/dist/install_local_dependencies.sh
++RUN /vt/dist/install_local_dependencies.sh
++RUN echo "source /vt/local/env.sh" >> /etc/bash.bashrc
++
++# Allows some docker builds to disable CGO
++ARG CGO_ENABLED=0
++
++# Re-copy sources from working tree.
++COPY --chown=vitess:vitess . /vt/src/vitess.io/vitess
++
++# Build and install Vitess in a temporary output directory.
++USER vitess
++
++WORKDIR /vt/src/vitess.io/vitess
++RUN make install PREFIX=/vt/install
++
++ENV VTROOT /vt/src/vitess.io/vitess
++ENV VTDATAROOT /vt/vtdataroot
++ENV PATH $VTROOT/bin:$PATH
++ENV PATH="/var/opt/etcd:${PATH}"
++
++RUN mkdir /vt/local
++RUN cp -r /vt/src/vitess.io/vitess/examples/local/* /vt/local
++# COPY examples/local /vt/local
++
++RUN mkdir /vt/common
++RUN cp -r /vt/src/vitess.io/vitess/examples/common/* /vt/common
++# COPY examples/common /vt/common
++
++
++CMD cd /vt/local && ./vtdriver/vtdriver_init.sh && /bin/bash
+Index: docker/lite/install_dependencies.sh
+IDEA additional info:
+Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
+<+>UTF-8
+===================================================================
+diff --git a/docker/lite/install_dependencies.sh b/docker/lite/install_dependencies.sh
+--- a/docker/lite/install_dependencies.sh	(revision aa798b854a0d12db8151157919108eaefb2378b2)
++++ b/docker/lite/install_dependencies.sh	(date 1646118958243)
+@@ -156,6 +156,7 @@
+ mysql56|mysql57|mysql80)
+     # repo.mysql.com
+     add_apt_key 8C718D3B5072E1F5
++    add_apt_key 467B942D3A79BD29
+     ;;
+ mariadb|mariadb103)
+     # digitalocean.com
